### ISSUE TITLE
add registration amount and download button 

### ISSUE THREAD

**Issue by tharoosha** [weyora-digital/ArenaSync#28]
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/3f0dcbda-2f9e-42b0-b12d-581a169b1bb5">

here remove showing adminid field and add number of registration and download action button for download registered participants details. I'll give you the API for get the registered users details

**Comment by tharoosha** [comment]
<img width="600" alt="image" src="https://github.com/user-attachments/assets/fea5eb81-1a4b-40bc-b946-041b5f64d969">

**Comment by raveeshavishwajith** [comment]
![image](https://github.com/user-attachments/assets/a72c43df-2375-4325-a4dc-ca0e5f1317cd)
Add number of registration and download action button.

![image](https://github.com/user-attachments/assets/f624c7e2-1658-4205-8784-80f00b9de74a)
when click the download button, we can download the event registration details as a excel sheet.

committed these changes to the test
