### ISSUE TITLE
Admin logout

### ISSUE THREAD

**Issue by tharoosha** [weyora-digital/ArenaSync#7]
admin logout routes should be developed and in the frontend admin pannel admin logout button should be displayed

**Comment by tharoosha** [comment]
do not need to add logout routes in the backend. since I already passed the jwt tokens, what you have to do is clear the jwt token in the local storage and navigate to the admin login page

function logout() {
    localStorage.removeItem('access_token');  // or remove it from cookies if stored there
    localStorage.removeItem('refresh_token');
    window.location.href = '/login';  // Redirect to login or another page
}

**Comment by raveeshavishwajith** [comment]
Admin logout implemented: tokens cleared and redirected to login.
